### ISSUE TITLE
Copy and branding issues

### ISSUE THREAD

**Issue by PieterJanPauwels** [openknowledgebe/diplohack-brussels#1]
Address field: 
Justus Lipsius Building
Council of the European Union
Rue de la Loi / Wetstraat 175 
1048 Bruxelles / Brussels
Belgium

**More information**
Title: More information:

First column: Who can participate?
We will create multi-skilled teams based on the different profiles who are present. We invite diplomats, journalists, developers, designers, students, citizens, civil society actors, social entrepreneurs, academics and basically anyone who wants to use and re-use transparency data to hack diplomatic issues. If you feel this topic appeals to you then you are more than welcome.

Second column: 
The Diplohack
A Diplohack is a hackathon focused on creating transparency applications. This means creating new, collaborative and creative methods for diplomacy and thus giving citizens more insights and usable information about decision making.

The Datad(r)ive
Before the Diplohack starts we will host a webinar together with the EU institutions to talk about the available data and the technical details. This webinar is open for everyone and you can ask questions about the data to prepare for TransparencyCamp Brussels. For the webinar, you need to register separately on Eventbrite.  

Third Column: 
The data
The Council of the European Union and the EU institutions already have an extensive catalogue of open datasets, which you can use to build your application.
On the EU Open Data Portal you can see which European datasets are already available. On the European Data Portal you can find data from all member states as well.

**Location**
Title: LOCATION
The Justus Lipsius Building is a unique location for any diplohacker, have a look at what rooms and amenities will be available.

**Programme**
Title: Programme
Title first column: Friday 29 April
08:30 - Doors
09:00 - Introduction & Policy Datad(r)ive 
10:00 - Break
10:30 - Ideation track
12:00 - Lunch
13:00 - Ideation track 2
14:00 - Start diplohack

Title second column: Saturday 30 April
08:00 - Breakfast
09:00 - Diplohack
12:00 - Lunch
14:00 - End of diplohack - prep presentation
15:00 - Pitching presentations
17:00 - Jury deliberation
18:00 - Award ceremony and closing reception

**Sign Up**
Title: SIGN UP ON
Logo: Eventbrite
Subtitle: TransparencyCamp Brussels is a collaboration between the Council of the European Union, the Netherlands EU Presidency and Open Knowledge Belgium.

**Awards**:
Title: First Prize
Subtitle: Go from Brussels to Washington

First time-node: TransparencyCamp Brussels
Join us at the Brussels diplohack and you might be part of the team that wins a ticket for two people to go to the next round and pitch your idea at the TransparencyCamp Europe unconference in Amsterdam. Other Brussels teams can still submit their application in the [online competition](https://transparencycamp.eu/app-competition/). 

Second time-node: TransparencyCamp Europe
All the winners of the local Diplohacks and the online competition get to present their application and pitch to an international jury of experts during the unconference. The winning team will receive a two-night stay in and flights to Washington, DC and special tickets to TransparencyCamp USA in September.
Link: https://transparencycamp.eu/

Third time-node: TransparencyCamp USA
At this global transparency event the winning team will get to pitch their idea and attend  the unconference that is completely focused on open government. Meet new people and influencers to make transparency happen. 
Link: https://www.youtube.com/watch?v=GqT-BXBqiHc

**Newsletter**: 
- Change header from "SUBSCRIBE TO OUR NEWSLETTER" to "SUBSCRIBE TO THE TRANSPARENCYCAMP EUROPE NEWSLETTER"
- Change code to mailchimp code of Open State

**Footer**:
- Replace "© 2016 Council of the EU" with "Source code freely available on GitHub (Logo)"
- Add round Open Knowledge Logo (https://drive.google.com/file/d/0B-uNSfOQ-TR_LVAyWV9EeV9NWlE/view?usp=sharing)
- Change Hashtag to: #TCampEU

**Comment by simonGSC** [comment]
Some comments:
In 'Who can participate'
instead "... basically anyone who wants to use and re-use transparency data to hack diplomatic issues:"
write: "... basically anyone who want to use and re-use public open data to hack diplomatic issues:" 
Reason: what is 'transparency data'? :)

in "The data"
Proposal: "The Council of the European Union and the EU institutions already have an extensive catalogue of open datasets, which you can use to build your application. These cover many different aspects, including Politics, Law, Transparency and Finance.
On the EU Open Data Portal you can see which datasets are already available. "
also, add a link to  the EU ODP?
Reason: there are no Member State data on the EU open data portal. It may be good to illustrate the breadth of avilalbe data.

In "Datad(r)ive"
should we add the date to the Data drive? 8 April, afaik.

**Comment by PieterJanPauwels** [comment]
Thanks Simon for the comments. We've implemented them together with the rebranding to diplohack.
